baseURL: "https://example.com/"
title: "New Landing"
theme: "PaperMod"

params:
  defaultTheme: dark
  disableThemeToggle: true

  profileMode:
    enabled: true
    title: "PaperMod is working"
    subtitle: "Minimal landing page"
